const assert=require('node:assert/strict');
const fs=require('node:fs');
const api=require('../app/job_profile/reviewer_assets/reviewer.js');
const html=fs.readFileSync(process.argv[2],'utf8');
const data=JSON.parse(html.match(/<script id="review-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
function reviewed(){const w=api.fresh(data),r=w.reviews[w.current_job_id];r.reviewer_id='synthetic-reviewer';r.reviewed_at='2026-10-07T12:00:00Z';return w;}
function label(r,key,value){r.labels[key]={state:'known',value,notes:null,evidence_text:null,item_details:[]};}
const key=data.jobs[0].input.job_id;
test('exact frozen 60 distinct jobs',()=>assert.equal(new Set(data.jobs.map(j=>j.input.job_id)).size,60));
test('all nine families',()=>assert.equal(new Set(data.jobs.flatMap(j=>j.sources)).size,9));
test('predictions never prefill human values',()=>{const w=api.fresh(data);for(const r of Object.values(w.reviews))for(const l of Object.values(r.labels)){assert.equal(l.state,'unlabeled');assert.equal(l.value,null);}assert.equal(api.summary(w).untouched,60);});
test('fresh state does not mutate embedded templates',()=>{const w=api.fresh(data);label(w.reviews[key],'job_family','Engineering');assert.equal(data.jobs[0].blank_review.labels.job_family.value,null);});
test('partial review is not complete',()=>{const w=reviewed();label(w.reviews[key],'career_level','senior');assert.equal(api.status(w.reviews[key]),'partial');assert.equal(api.summary(w).completed,0);});
test('explicit complete flag',()=>{const w=reviewed();label(w.reviews[key],'career_level','senior');w.reviews[key].review_complete=true;assert.equal(api.summary(w).completed,1);});
test('known false preserved',()=>{const w=reviewed();label(w.reviews[key],'is_normal_vacancy',false);assert.equal(api.exportRows(w,data)[0].labels.is_normal_vacancy.value,false);});
test('unknown not-mentioned ambiguous states survive',()=>{const w=reviewed();for(const [i,state] of ['unknown','not_mentioned','ambiguous'].entries())w.reviews[key].labels[['job_family','people_management','workplace'][i]]={state,value:null,notes:'uncertain',item_details:[],evidence_text:'original'};const r=api.importText(api.exportJSONL(w,data),data,api.fresh(data));assert.equal(r.reviews[key].labels.workplace.state,'ambiguous');});
test('multi-value mentions and skills remain separate',()=>{const w=reviewed();label(w.reviews[key],'technologies',['Python','SQL']);label(w.reviews[key],'required_skills',['Data modeling']);assert.equal(api.importText(api.exportJSONL(w,data),data,api.fresh(data)).reviews[key].labels.required_skills.value[0],'Data modeling');assert.equal(w.reviews[key].labels.required_technologies.state,'unlabeled');});
test('JSONL round trip preserves completion evidence and identity',()=>{const w=reviewed();label(w.reviews[key],'people_management',true);w.reviews[key].labels.people_management.evidence_text='Manage a team of five';w.reviews[key].review_complete=true;const r=api.importText(api.exportJSONL(w,data),data,api.fresh(data));assert.deepEqual(r.reviews,w.reviews);});
test('CSV round trip preserves multiline notes',()=>{const w=reviewed();label(w.reviews[key],'normalized_role','Engineer');w.reviews[key].reviewer_notes='Line 1, with "quotes"\nLine 2';const r=api.importText(api.exportCSV(w,data),data,api.fresh(data));assert.deepEqual(r.reviews,w.reviews);});
test('CEFR lower upper range comparators preserved',()=>{for(const comparator of ['exact','at_least','at_most','range','unknown']){const w=reviewed();label(w.reviews[key],'languages',[{language:'en',requirement:'required',cefr:'B2',cefr_comparator:comparator,cefr_max:comparator==='range'?'C1':null,cefr_or_higher:comparator==='at_least',cefr_state:'known',original_wording:'B2 wording'}]);const r=api.importText(api.exportJSONL(w,data),data,api.fresh(data));assert.equal(r.reviews[key].labels.languages.value[0].cefr_comparator,comparator);}});
test('fluent wording does not become CEFR',()=>{const w=reviewed();label(w.reviews[key],'languages',[{language:'en',requirement:'required',cefr:null,cefr_state:'not_mentioned',original_wording:'fluent English'}]);assert.equal(api.exportRows(w,data)[0].labels.languages.value[0].cefr,null);});
test('invalid CEFR range rejected',()=>{const w=reviewed();label(w.reviews[key],'languages',[{language:'en',requirement:'unknown',cefr:'C1',cefr_comparator:'range',cefr_max:'B2'}]);assert.throws(()=>api.exportJSONL(w,data),/ordered upper/);});
test('completed export is subset only',()=>{const w=reviewed();label(w.reviews[key],'career_level','senior');w.reviews[key].review_complete=true;assert.equal(api.exportRows(w,data,true).length,1);});
test('different cohort input rejected atomically',()=>{const w=reviewed();label(w.reviews[key],'career_level','senior');const rows=api.exportRows(w,data);rows[1].profile_input_hash='f'.repeat(64);const old=JSON.stringify(w);assert.throws(()=>api.importText(rows.map(r=>JSON.stringify(r)).join('\n'),data,w),/frozen input/);assert.equal(JSON.stringify(w),old);});
test('duplicate import requires adjudication',()=>{const r=reviewed().reviews[key];assert.throws(()=>api.importText(JSON.stringify([r,r]),data,api.fresh(data)),/Duplicate/);});
test('prediction file cannot be imported as labels',()=>assert.throws(()=>api.importText(JSON.stringify(data.jobs[0].prediction),data,api.fresh(data)),/unknown job/));
test('draft backup preserves invalid unfinished fields',()=>{const w=reviewed();label(w.reviews[key],'base_compensation',[]);assert.throws(()=>api.exportJSONL(w,data),/Known needs/);assert.deepEqual(api.importText(JSON.stringify(w),data,api.fresh(data)).reviews,w.reviews);});
test('old human schema gains only unlabeled extension fields',()=>{const w=reviewed(),r=w.reviews[key];r.label_schema_version='job-profile-human-v1.1';for(const f of ['required_skills','preferred_skills','base_compensation_present'])delete r.labels[f];const imported=api.importText(JSON.stringify(r),data,api.fresh(data));assert.equal(imported.reviews[key].labels.required_skills.state,'unlabeled');});
test('separate compensation offers preserved',()=>{const w=reviewed();label(w.reviews[key],'base_compensation',[{min_amount:'80000',max_amount:'100000',currency:'CZK',period:'month',component:'base',gross_net_status:'unknown',applicable_locations:['Prague']},{min_amount:'60000',max_amount:null,currency:'EUR',period:'year',component:'base',gross_net_status:'unknown',applicable_locations:['Paris']}]);assert.equal(api.exportRows(w,data)[0].labels.base_compensation.value.length,2);});
test('reviewer metadata required for export',()=>{const w=api.fresh(data);label(w.reviews[key],'career_level','senior');assert.throws(()=>api.exportJSONL(w,data),/reviewer name/);});
test('blind-first DOM order and panels closed',()=>{assert(html.indexOf('id="original"')<html.indexOf('id="human"'));assert(html.indexOf('id="human"')<html.indexOf('id="prediction"'));assert(!/<details id="(?:prediction|suggestions)"[^>]*\bopen/.test(html));});
fs.writeFileSync('/analysis/js-tests.json',JSON.stringify({tests:count,passed:count}));
console.log(JSON.stringify({tests:count,passed:count}));
